import type { NextPage } from 'next'
import Head from 'next/head'
// recoilからatomをimport
import { atom, useRecoilState } from 'recoil'
import CheckboxItem from '../components/checkItem'
import styles from '../styles/Home.module.css'

export const todoTaskState = atom({
  key: 'task',
  default: [
    '昼寝をする',
    '超昼寝をする',
    '超超昼寝をする',
    '超超超昼寝をする',
  ],
})

export const inputFormState = atom({
  key: 'inputForm',
  default: ''
})

const Home: NextPage = () => {
  const [todoTasks, setTodoTasks] = useRecoilState(todoTaskState)
  const [inputForm, setInputForm] = useRecoilState(inputFormState)

  const addTaskItem = () => {
    if(inputForm!="") {
      setTodoTasks([
        ...todoTasks, inputForm
      ])
      setInputForm("")
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Next ToDO App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Todoリスト</h1>
        <h3>新しくやること</h3>
        <div>
          <input value={inputForm} onChange={(e)=>{ setInputForm(e.target.value) }} />
          <button onClick={()=>addTaskItem()}>決定</button>
        </div>
        <ul>
          {
            todoTasks.map((item,index) => {
              return <CheckboxItem id={index}>{item}</CheckboxItem>
            })
          }
        </ul>
      </main>
    </div>
  )
}

export default Home
