import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { atom, useRecoilState, useRecoilValue, useSetRecoilState } from 'recoil'
import CheckboxItem from '../components/checkItem'
import styles from '../styles/Home.module.css'

export const todoTaskState = atom({
  key: 'task',
  default: [
      '昼寝をする',
      '超昼寝をする',
      '超超昼寝をする',
      '超超超昼寝をする',
    ],
})

export const inputFormState = atom({
  key: 'inputForm',
  default: ''
})

const Home: NextPage = () => {
  const [tasksList, setTasksList] = useRecoilState(todoTaskState)
  const [inputForm, setInputForm] = useRecoilState(inputFormState);
  const addTaskItem = () => {
    if(inputForm!="") {
      setTasksList([
        ...tasksList, inputForm
      ])
      setInputForm("")
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Next ToDO App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Todoリスト</h1>
        <div>新しくやること</div>
        <div className={styles.formSubmitButton}>
          <input value={inputForm} onChange={(e)=>{ setInputForm(e.target.value) }} />
          <button onClick={()=>addTaskItem()}>決定</button>
        </div>
        <ul>
          {
            tasksList.map((item, index) => {
              return <CheckboxItem id={index}>{item}</CheckboxItem>
            })
          }
        </ul>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
